<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  
  <!--<ItemGroup>
    <AvaloniaXaml Remove="App.axaml" />
    <AvaloniaXaml Remove="LevelManager\LevelViews\Level1View.axaml" />
    <AvaloniaXaml Remove="LevelManager\Otazky\ABCDOtazkaView.axaml" />
    <AvaloniaXaml Remove="LevelManager\Otazky\VstupnaOtazkaView.axaml" />
    <AvaloniaXaml Remove="Views\LevelyOverviewView.axaml" />
    <AvaloniaXaml Remove="Views\MainView.axaml" />
    <AvaloniaXaml Remove="Views\MainWindow.axaml" />
    <AvaloniaXaml Remove="Views\NastaveniaOverviewView.axaml" />
    <AvaloniaXaml Remove="Views\VysvetlivkyOverviewView.axaml" />
  </ItemGroup>-->
	<!-- Rely on Avalonia SDK defaults to include .axaml files for compilation. -->

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\NastaveniaOverviewView.axaml.cs">
      <DependentUpon>NastaveniaOverviewView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\VysvetlivkyOverviewView.axaml.cs">
      <DependentUpon>VysvetlivkyOverviewView.axaml</DependentUpon>
    </Compile>
    <Compile Update="VysvetlivkyManager\Vysvetlivka1View.axaml.cs">
      <DependentUpon>Vysvetlivka1View.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
